language: java
jdk:
  - openjdk8
branches:
  only:
    - master
    -
before_install:
  - chmod +x gradlew
#Travis CI 서버의 Home
before_deploy:
  - zip -r springboot-chap1_1 *
  - mkdir -p deploy # travis CI가 실행중인 위치에 deploy 폴더 생성한다.
  - mv springboot-chap1_1.zip deploy/springboot-chap1_1.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # travis CI Settings에 값을 설정했다.
    secret_access_key: $AWS_SECRET_KEY
    bucket: ck-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근은 private
    local_dir: deploy # before_deploy에서 생성한 폴더이름
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ck-springboot-build
    key: springboot-chap1_1.zip
    bundle_type: zip
    application: springboot-chap1_1 # 웹콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: springboot-test-group # 웹콘솔에서 등록한 codeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행완료시 메일로 알람

notifications:
  email:
    recipients:
      - kjc132@naver.com
